clear
close all
clc

power_budget = 25;
period = 8.8294e3;
eclipse_time = 0.4*period; % worst case in one year [s]
daylight_time = period - eclipse_time; % eclpise time [s]
X_e = 0.6;
X_d = 0.8;
P_e = power_budget; % power required during daylight [W]
P_d = P_e; % power required during eclpise [W]
P_sa = ((P_e*eclipse_time/X_e) + (P_d*daylight_time/X_d))/daylight_time; % total power required [W]

P_0 = 1353; % base power generated by the solar arrays [W/m^2]
EOL_efficiency = 0.268; % End of Life efficiency
P_gen = P_0 * EOL_efficiency; % nominal power generation [W/m^2]

I_d = 0.72; % inherent nominal degradation
incidence_angle = 30*pi/180; % Sun incidence angle [rad]
P_eff = P_gen * I_d * cos(incidence_angle); % worst-case deliverable power [W]

cells_surface = P_sa / P_eff % total surface of the solar panels [m^2]

batteries = P_e * eclipse_time / 3600 * 3